#!make
########################## Variables #####################
DOCKER		    ?= docker
DOCKER_COMPOSE  ?= docker-compose -p enterprise-php-dist
CWD             := $(shell pwd | sed 's/ /\\ /g')
TZ				?= Europe/London
##########################################################

V ?= $(VERBOSE)
ifeq ("$(V)","1")
	Q			:=
	vecho		:= @true
else
	Q			:= @
	vecho		:= @echo
endif

##### Makefile related #####
.PHONY: all up info clean data-clean docker-up

default: help

##@ Docker related

logs: ## Show docker-compose logs command
	$(Q) $(DOCKER_COMPOSE) logs -f

docker-clean: ## Destroy the system
	@echo ""
	@echo "\033[92mDestroying the 'docker-compose' infrastructure and services...\033[0m"
	@echo ""
	$(Q) $(DOCKER_COMPOSE) rm -fsv
	$(Q) $(DOCKER_COMPOSE) down --remove-orphans

docker-up: ## Start application
	@echo ""
	@echo "\033[92mStarting the 'docker-compose' infrastructure and services...\033[0m"
	@echo ""
	$(Q) $(DOCKER_COMPOSE) up -d --build --remove-orphans
	$(Q) $(DOCKER_COMPOSE) ps

info: ## Show info
	@echo ""
	@echo "\033[92mSetup Info\033[0m"
	@echo ""
	$(Q) $(DOCKER) ps -a

##@ Utils

transient-files-clean: ## Removing files generated by the automations and servers
	@echo ""
	@echo "\033[92mRemoving generated (if) logs, pid, stats and cache files...\033[0m"
	@echo ""
	$(Q) rm -rf ./dal/application/data/cache/* ./dal/.docker/entrypoint.d/runfile
	@echo ""

create-schema: ## Creating DB schema using doctrine
	@echo ""
	@echo "\033[92mCreating DB schema using Doctrine...\033[0m"
	@echo ""
	$(Q) $(DOCKER) exec dal /dal/bin/doctrine orm:schema-tool:create
	@echo ""

##@ Main Targets

all: docker-up ## Load the system

clean: docker-clean transient-files-clean ## Clean all

##@ Help

help:  ## Display this help
	@awk 'BEGIN {FS = ":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n"} /^[a-zA-Z_-]+:.*?##/ { printf "  \033[36m%-40s\033[0m %s\n", $$1, $$2 } /^##@/ { printf "\n\033[1m%s\033[0m\n", substr($$0, 5) } ' $(MAKEFILE_LIST)

